class FILE:
    def __init__(self, *args, **kwargs) -> None: ...

class MirrorClientDataStore:
    def __init__(self) -> None: ...
    def join(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class Version:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def get_long_product_name() -> str: ...
    @staticmethod
    def get_short_product_name() -> str: ...
    @staticmethod
    def get_version() -> int: ...
    @staticmethod
    def get_version_string() -> str: ...
    @staticmethod
    def get_version_token() -> tuple[int, int, int, str]: ...

class descr:
    def __init__(self, *args, **kwargs) -> None: ...

class elem:
    def __init__(self, *args, **kwargs) -> None: ...

def get_JB_Type() -> descr: ...
def get_field() -> int: ...
def get_stdout() -> FILE: ...
def lCreateElem(arg0: descr) -> elem: ...
def lGetUlong(arg0: elem, arg1: int) -> int: ...
def lSetUlong(arg0: elem, arg1: int, arg2: int) -> int: ...
def lWriteElemTo(arg0: elem, arg1: FILE) -> None: ...
